// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310162554_ColumnParentIdAndDatesForCategories")]
    partial class ColumnParentIdAndDatesForCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Product.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("Backend.Models.Product.AttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.ToTable("AttributesValues");
                });

            modelBuilder.Entity("Backend.Models.Product.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desktops",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptops",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mini PCs",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "All-in-One PCs",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Computer Components",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Processors (CPU)",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 8,
                            Name = "Graphics Cards (GPU)",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "Motherboards",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 10,
                            Name = "Memory (RAM)",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 11,
                            Name = "Solid State Drives (SSD)",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hard Drives (HDD)",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 13,
                            Name = "Power Supplies",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 14,
                            Name = "Computer Cases",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 15,
                            Name = "Cooling Systems",
                            ParentId = 6
                        },
                        new
                        {
                            Id = 16,
                            Name = "Peripherals",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 17,
                            Name = "Keyboards",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 18,
                            Name = "Mice",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mouse Pads",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 20,
                            Name = "Monitors",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 21,
                            Name = "Webcams",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 22,
                            Name = "Headsets",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 23,
                            Name = "Speakers",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 24,
                            Name = "Microphones",
                            ParentId = 16
                        },
                        new
                        {
                            Id = 25,
                            Name = "Networking",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 26,
                            Name = "Routers",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 27,
                            Name = "Network Switches",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 28,
                            Name = "Network Adapters",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 29,
                            Name = "Modems",
                            ParentId = 25
                        },
                        new
                        {
                            Id = 30,
                            Name = "Storage Devices",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 31,
                            Name = "External Hard Drives",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 32,
                            Name = "External SSDs",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 33,
                            Name = "USB Flash Drives",
                            ParentId = 30
                        },
                        new
                        {
                            Id = 34,
                            Name = "Memory Cards",
                            ParentId = 30
                        });
                });

            modelBuilder.Entity("Backend.Models.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend.Models.Product.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Backend.Models.Product.VariantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeValueId")
                        .HasColumnType("integer");

                    b.Property<int>("VariantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributeValueId");

                    b.HasIndex("VariantId");

                    b.ToTable("VariantAttributes");
                });

            modelBuilder.Entity("Backend.Models.Product.AttributeValue", b =>
                {
                    b.HasOne("Backend.Models.Product.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");
                });

            modelBuilder.Entity("Backend.Models.Product.Product", b =>
                {
                    b.HasOne("Backend.Models.Product.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.Product.ProductVariant", b =>
                {
                    b.HasOne("Backend.Models.Product.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product.VariantAttribute", b =>
                {
                    b.HasOne("Backend.Models.Product.AttributeValue", "AttributeValue")
                        .WithMany()
                        .HasForeignKey("AttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product.ProductVariant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");

                    b.Navigation("Variant");
                });
#pragma warning restore 612, 618
        }
    }
}
